### ISSUE TITLE
Erro ao gerar output

### ISSUE THREAD

**Issue by ksrx** [davidboto/SinacorPdfParser#1]
Ola, tudo bem?

Fui testar o seu sistema e esta com o seguinte erro ao tentar gerar a saida:

# java -jar build/libs/SinacorPDFParser-all.jar nota_4131.pdf 
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at sinacorpdfparser.Cliente.getAcumulado(Cliente.java:81)
	at sinacorpdfparser.Cliente.executar(Cliente.java:98)
	at sinacorpdfparser.App.main(App.java:27)

Obrigado e parabens pelo trabalho.

**Comment by davidboto** [comment]
@ksrx , obrigado por reportar o problema. Acredito que o problema seja por conta do template. Atualmente só estou tratando das notas de operações na BM&F. 

Vou agilizar para tratar também as notas de operações na Bovespa nos próximos dias. 

Obrigado pelo feedback.

**Comment by ksrx** [comment]
Ola David,

Existe ainda essa diferenciação? Achei que desde a fusão BMF/Bovespa não existia tal diferença da descrição na nota de um ativo no mercado a vista ou futuro.

Meu teste foi usando uma nota do Itau e do Inter. Mas realmente foram compras no mercado a vista.

Quando conseguir me informe que terei prazer em testar.

abs

**Comment by ksrx** [comment]
Ola David,

Vi que vc commitou suporte a bovespa, porém estou tendo ainda o seguinte erro:

Exception in thread "main" java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at java.util.regex.Matcher.group(Matcher.java:496)
	at sinacorpdfparser.Parser.tokenizeBov(Parser.java:120)
	at sinacorpdfparser.Parser.extract(Parser.java:93)
	at sinacorpdfparser.Cliente.getNotasNegociacao(Cliente.java:58)
	at sinacorpdfparser.Cliente.executar(Cliente.java:101)
	at sinacorpdfparser.App.main(App.java:27)

**Comment by davidboto** [comment]
Olá @ksrx , 

Obrigado novamente por se dispor a testar.

Realmente fiz alguns ajustes para suportar as notas de corretagem na bovespa, mas apesar de seguirem o modelo do SINACOR, os .pdfs gerados pelas corretoras infelizmente podem ser bem diferentes, daí o motivo de alguns erros como estes que vc reportou.

Como ainda não tenho acesso à outros modelos de notas de corretagem, consigo tratar basicamente as notas emitidas por somente duas corretoras. :(

**Comment by ksrx** [comment]
Bom dia David,

Quais corretoras voce esta usando para testes? eu testei com notas do itau e inter.

**Comment by davidboto** [comment]
Boa tarde @ksrx ,

Estou usando os templates da rico e clear, ou seja, ainda é um universo muito pequeno de corretoras que são suportadas. :(

**Comment by ksrx** [comment]
David,

Eu usei uma nota da rico e nao deu certo:

DataPregao;NrNotaNegociacao;debentures;vendasAVista;comprasAVista;opcoesCompras;opcoesVendas;operacoesATermo;valorDasOpTitulosPublicos;valorDasOperacaoes;totalCBLC;valorLiquidoDasOperacoes;taxaDeLiquidacao;taxaDeRegistro;totalBovespa;taxaDeTermo;taxaANA;emolumentos;totalCustos;taxaOperacional;execucao;taxaDeCustodia;imposto;IRRF;outros;liquido
03/09/2012;175053;0.0;0.0;4047.2;0.0;0.0;0.0;0.0;4047.2;4048.31;4047.2;1.11;0.0;0.28;0.0;0.0;0.28;0.0;0.0;0.0;0.0;0.0;0.0;0.0;4048.59


N?o foi poss?vel extrair os campos da(s) nota(s) informada(s). 
Padr?es suportados: nota de corretagem de opera??es na BM&F e Bovespa. 
Testado para as corretoras: Rico e Clear

**Comment by davidboto** [comment]
@ksrx , boa noite! 

Mais uma vez, obrigado. Esse primeiro trecho, q inicia com "DataPregao" e termina com "4048.59", é o csv. Vc pode salvar isso em um .csv e abrir no google calcs, excel ou libreoffice calc que eles devem reconhecer sem problema.

Nas versões mais recentes desse código os arquivos .csv e .json são gerado automaticamente e armazenados na pasta `output`.

Acredito que a mensagem de erro é exibida porque o parser tentou converter a sua nota considerando também a estrutura utilizada pela BM&F. 

Considerando que o seu código é o mais recente, a chamada abaixo deve funcionar sem exibir mensagem de erro:

`java -jar --arquivo arquivo.pdf -bovespa -bmf -csv`

Além de exibir o csv, como ocorreu na última vez, será gerado um .csv na pasta `output` do projeto.

Espero que isso possa ajudar e qlqr coisa estamos por aqui. o/
